name : fall
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.1
  - pip
  - pip:
    - gdown==4.7.3
    - matplotlib==3.7.2
    - pandas==2.0.3
    - pillow==9.3.0
    - numpy==1.24.4
    - segment-anything==1.0
    - semantic-version==2.10.0
    - torch==2.0.1
    - torchmetrics==1.0.0
    - torchvision==0.15.2
    - torchaudio==2.0.2
    - tqdm==4.65.0
    - transformers==4.29.0
    - seaborn
    - scikit-learn
    - scikit_image==0.22.0
    - pycaret[full]
    - -e git+https://github.com/IDEA-Research/GroundingDINO.git@main#egg=GroundingDINO